fruits = []
f1 = input("Entre fruit name: ")
fruits.append(f1)
f2 = input("Entre fruit name: ")
fruits.append(f2)
f3 = input("Entre fruit name: ")
fruits.append(f3)
f4 = input("Entre fruit name: ")
fruits.append(f4)
f5 = input("Entre fruit name: ")
fruits.append(f5)
f6 = input("Entre fruit name: ")
fruits.append(f6)
f7 = input("Entre fruit name: ")
fruits.append(f7)
print(fruits)