a = set()

n1 = input("entre number: ")
a.add(n1)
n2 = input("entre number: ")
a.add(n2)
n3 = input("entre number: ")
a.add(n3)
n4 = input("entre number: ")
a.add(n4)
n5 = input("entre number: ")
a.add(n5)
n6 = input("entre number: ")
a.add(n6)
n7 = input("entre number: ")
a.add(n7)
n8 = input("entre number: ")
a.add(n8)

print(a)